
#biome-distribution:
  # Biome distribution refers to the placement of biomes, this does *NOT*
  # include aspects like terrain height / shape within biomes, or anything
  # else that generates within any given biome.
  
  # These parameters are designed to allow for easy modification of biome distribution,
  # and are injected into the various biome distribution configs via meta-configuration.
  # You can find these configs in the biome-providers directory, most of which contain
  # additional more specific parameters.


# Misc global config stuff
